### ISSUE TITLE
Mobile viewport Testimonials [ bug ] 

### ISSUE THREAD

**Issue by robbiekruszynski** [OneMillionDevs/1md-site#1]
![Image from iOS](https://user-images.githubusercontent.com/41847310/73221469-ce54bd00-4115-11ea-95ca-51b4d317058b.png)

- [ ] Adjust styles from 770x  - 980x on homepage 
breakpoint issues occurring with text overflow 
- [ ] check margins

***side note ****
good tool to more accurately test mobile renderings 
https://www.browserstack.com/

**Comment by orbro** [comment]
resolved
