### ISSUE TITLE
Cards viewport variations issues [ bug ] 

### ISSUE THREAD

**Issue by robbiekruszynski** [OneMillionDevs/1md-site#3]
link : https://onemilliondevs.com/developer-resources/
![Image from iOS (1)](https://user-images.githubusercontent.com/41847310/73222457-24c2fb00-4118-11ea-8534-c7783625d7b4.png)

In a mobile viewport, card ( experience + img) are pushed to the right 
other cards in the section render correctly 
- [ ] adjust margin 
- [ ] spacing on Acquire, Aquire your ETH needs revision also

**Comment by orbro** [comment]
resolved
